export const SCREENS = {
  /* TAB BAR */
  Home: "HomeScreen",
  Venue: "VenueScreen",
  Chat: "ChatScreen",
  Profile: "ProfileScreen",

  /* LOGIN & REGISTER */
  Initial: "InitialScreen",
  Root: "RootScreen",
  PhoneLogin: "PhoneLoginScreen",
  PhoneVerification: "PhoneVerificationScreen",
  Username: "UsernameScreen",
  Name: "NameScreen",
  ProfilePictureLogin: "ProfilePictureLoginScreen",

  /* STACK */
  Camera: "CameraScreen",
  VenueDetail: "VenueDetailScreen",
  UserPosts: "UserPostsScreen",
  BusinessPosts: "BusinessPostsScreen",
  Search: "SearchScreen",
  UserFeed: "UserFeedScreen",
  EditProfile: "EditProfileScreen",
  PhotoCrop: "PhotoCropScreen",
  Settings: "SettingsScreen",
  EditBusinessPost: "EditPostScreen",
  EditUserPost: "EditUserPostScreen",
  SortSlices: "SortSlicesScreen",
  VenueRanking: "VenueRankingScreen",
  Web: "WebViewScreen",
  StoryActivity: "StoryActivityScreen",
  Map: "MapScreen",
  MyMomentDetails: "MyMomentDetailsModal",
  UserMoments: "UserMomentsScreen",
  UserEvents: "UserEventsScreen",
  ChatMessage: "ChatMessageScreen",
  CreateMoment: "CreateMomentScreen",
  CreateEvent: "CreateEventScreen",
  PreviewMoment: "PreviewMomentScreen",
  Spots: "SpotsScreen",
  CreateSpot: "CreateSpotScreen",
  BusinessSpots: "BusinessSpotsScreen",
  QrScanner: "QrScannerScreen",
  BusinessMoments: "BusinessMomentsScreen",
  MyMoments: "MyMomentsScreen",

  /* BUSINESS */
  BusinessHome: "BusinessHomeScreen",
  BusinessInsight: "BusinessInsightScreen",
  BusinessProfile: "BusinessProfileScreen",
  EditBusiness: "EditVenueScreen",
  BusinessFeed: "BusinessFeedScreen",
  BusinessInsightDetail: "BusinessInsightDetailScreen",
  ContactUs: "ContactUsModal",
  BusinessList: "BusinessListScreen",
  BusinessPosts: "BusinessPostsScreen",
  BusinessEventPreview: "BusinessEventPreviewScreen",
  MomentsList: "MomentsListScreen",
  EventDetail: "EventDetailScreen",
  EditLocationMap: "EditLocationMapScreen",
  EventUsersList: "EventUsersListScreen",
  UserSearch: "UserSearchScreen",
  BusinessShare: "BusinessShareModal",
  BusinessShareEvent: "BusinessShareEventModal",
  MyProfilesList: "MyProfilesListModal",
  SpotReplies: "SpotRepliesModal",
  MyEvents: "MyEventsScreen",

  //* MODALS *//
  AddLink: "AddLinkModal",
  CountryPicker: "CountryPickerModal",
  Successful: "SuccessfulModal",
  VenueFilter: "VenueFilterModal",
  VenueDescription: "VenueDescriptionModal",
  VenueMap: "VenueMapModal",
  MapSelector: "MapSelectorModal",
  VenueTimetable: "VenueTimetable",
  Reaction: "ReactionModal",
  AddLocation: "AddLocationModal",
  AddBusiness: "AddBusinessModal",
  AddClub: "AddClubModal",
  Share: "ShareModal",
  CustomVenueFeature: "CustomVenueFeatureModal",
  EditAddress: "EditAddressModal",
  Report: "ReportModal",
  Languages: "LanguagesModal",
  IncreaseVisiblity: "IncreaseVisiblityModal",
  MomentFilters: "MomentFiltersModal",
  EditUserInterests: "EditUserInterestsModal",
  Tutorial: "TutorialModal",
  ChangeProfilePicture: "ChangeProfilePictureModal",
  BusinessAllSet: "BusinessAllSetModal",
  EditBusinessInfo: "EditBusinessModal",
  MomentParticipants: "MomentParticipantsModal",
  AddParticipants: "AddParticipantsModal",
  SleekLogin: "SleekLoginModal",

  AlbumsList: "AlbumsListModal",
  DateTimePicker: "DateTimePickerModal",
  ChanceDetail: "ChanceDetailModal",

  ProfileStuffs: "ProfileStuffsModal",
  ChangePassword: "ChangePasswordModal",
  EditUsername: "EditUsernameModal",
  EditName: "EditNameModal",
  EditBio: "EditBioModal",
  EditPhone: "EditPhoneModal",
  EditInstagram: "EditInstagram",
  EditLink: "EditLinkModal",

  MenuModal: "MenuModal",
  SwitchProfile: "SwitchProfileModal",
  DeleteVenue: "DeleteVenueModal",
  InsightInfo: "InsightInfoModal",
  Calendar: "CalendarModal",

  InviteFriends: "InviteFriendsModal",
  ChooseBusinessToCreate: "ChooseBusinessToCreateModal",
  BusinessAcceptTerms: "BusinessAcceptTermsModal",
  ReserveOptions: "ReserveOptionsModal",
  EventParticipants: "EventParticipantsModal",
};
